'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Kairen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _64x64() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_64x64", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property a_badger() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("a_badger", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Address2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Address2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Address3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Address3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Address4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Address4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Address5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Address5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Alert_OutputPlayerData_ConsoleOutput2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Alert_OutputPlayerData_ConsoleOutput2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Alert_OutputPlayerData2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Alert_OutputPlayerData2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Alert_ProcessOutsideCommands2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Alert_ProcessOutsideCommands2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Aloj_Tilsteran() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Aloj_Tilsteran", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property an_undead_mammoth() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("an_undead_mammoth", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Angry_Patron() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Angry_Patron", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Arch_Familiar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Arch_Familiar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Area() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Area", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Bowyer_Koll() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Bowyer_Koll", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Box1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Box1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Box2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Box2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ChangeLog_GameContent() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ChangeLog_GameContent", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ChangeLog_GameContent2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ChangeLog_GameContent2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Changelog_GameContent3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Changelog_GameContent3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ChangeLog_KairenContent() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ChangeLog_KairenContent", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Changelog_KairenContent1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Changelog_KairenContent1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Changelog_KairenContent2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Changelog_KairenContent2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Changelog_KairenContent3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Changelog_KairenContent3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Changelog_KairenContent4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Changelog_KairenContent4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Changelog_KairenContent5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Changelog_KairenContent5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Coachman_Ronks() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Coachman_Ronks", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ConsoleOutput() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ConsoleOutput", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ConsoleOutput2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ConsoleOutput2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ConsoleOutput3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ConsoleOutput3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Convert_BooleanToString2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Convert_BooleanToString2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CreateNPCFile1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CreateNPCFile1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Custom_Settings1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Custom_Settings1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Custom1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Custom1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Dr_Killian() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Dr_Killian", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DualBox() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DualBox", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FAPI() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FAPI", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FAPI1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FAPI1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FAPI2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FAPI2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FAPI3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FAPI3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FAPI4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FAPI4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FAPI4pre() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FAPI4pre", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FAPI5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FAPI5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property File_Exists1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("File_Exists1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property File_Paths() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("File_Paths", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property File_Paths1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("File_Paths1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property File_Paths2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("File_Paths2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property File_Paths3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("File_Paths3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property File_Paths4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("File_Paths4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Finalquestt() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Finalquestt", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ghost() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ghost", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Green_Light_Icon_png() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Green_Light_Icon_png", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Guard_Jahn() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Guard_Jahn", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Guard_Perinen() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Guard_Perinen", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Guard_Saolen() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Guard_Saolen", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Guard_Serenda() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Guard_Serenda", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property HEX_DEC() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("HEX_DEC", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ihtol() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ihtol", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Kanizah() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Kanizah", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Kanizah2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Kanizah2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Kanizah3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Kanizah3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Kanizah4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Kanizah4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Left2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Left2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Locations() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Locations", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Main() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Main", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Main1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Main1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Main2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Main2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Main3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Main3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Main4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Main4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Main5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Main5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Main6() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Main6", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MainTable() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MainTable", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MainTable1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MainTable1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MainTable2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MainTable2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MainTableJustWorldPopulationKey() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MainTableJustWorldPopulationKey", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MainTableJustWorldPopulationKey_SilentMode() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MainTableJustWorldPopulationKey_SilentMode", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Manoarmz() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Manoarmz", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Marona_Jofranka() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Marona_Jofranka", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Merchant_Ahkham() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Merchant_Ahkham", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Merchant_Kari() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Merchant_Kari", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal_Settings1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal_Settings1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal_Settings2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal_Settings2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal_Settings3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal_Settings3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal_Settings4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal_Settings4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal_Settings4pre() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal_Settings4pre", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal4pre() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal4pre", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC_Files() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC_Files", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC_Maker() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC_Maker", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC4pre() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC4pre", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC6() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC6", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NPC7() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NPC7", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Nukenurplace() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Nukenurplace", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OutputPlayerData2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OutputPlayerData2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ProcessOutsideCommands1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ProcessOutsideCommands1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ProcessOutsideCommands2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ProcessOutsideCommands2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property PsuedoNormal_Settings1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PsuedoNormal_Settings1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property PsuedoNormal1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PsuedoNormal1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Raam() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Raam", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Randall_Adams1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Randall_Adams1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Read_BitArrayToString1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Read_BitArrayToString1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Read_BitArrayToString2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Read_BitArrayToString2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Read_BitArrayToString3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Read_BitArrayToString3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Read_BitArrayToString4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Read_BitArrayToString4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Read_FileToStringArray1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Read_FileToStringArray1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Read_FileToStringArray2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Read_FileToStringArray2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ReadNextLine1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ReadNextLine1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ReadNextLine2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ReadNextLine2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Red_Light_Icon_png() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Red_Light_Icon_png", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Right2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Right2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Royce_Tilsteran() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Royce_Tilsteran", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RunOptions1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RunOptions1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RunOptions2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RunOptions2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Settings_NPCMaker() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings_NPCMaker", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property sign_post() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("sign_post", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SpawnHandler2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpawnHandler2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SpawnHandler3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpawnHandler3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SpawnHandler4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpawnHandler4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property System_IO_Compression_FileSystem() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("System_IO_Compression_FileSystem", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Tailor_Bariston() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Tailor_Bariston", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Tailor_Zixar() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Tailor_Zixar", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Version() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Version", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Version1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Version1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property White_Light_Icon_png() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("White_Light_Icon_png", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property World_Population() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("World_Population", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property World_Population_Settings() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("World_Population_Settings", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property World_Population_Settings2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("World_Population_Settings2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property World_Population_Settings3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("World_Population_Settings3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property World_Population_Settings4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("World_Population_Settings4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property World_Population2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("World_Population2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property World_Population3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("World_Population3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Write_StringArrayToFile1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Write_StringArrayToFile1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Write_StringToBitArrayAddress1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Write_StringToBitArrayAddress1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Write_StringToBitArrayAddress2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Write_StringToBitArrayAddress2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Write_StringToBitArrayAddress3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Write_StringToBitArrayAddress3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Yellow_Light_Icon_png() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Yellow_Light_Icon_png", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
